# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  variacaoativoui:
    image: variacaoativoui
    build:
      context: .
      dockerfile: src/VariacaoAtivo.UI/Dockerfile
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      - "MSSQL_SA_PASSWORD=Password123!"
      - "ACCEPT_EULA=Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./scripts/:/docker-entrypoint-initdb.d
    restart: always

