CREATE DATABASE Ativos
GO

USE Ativos

CREATE TABLE Cota
(
	Id BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Dia INT NOT NULL,
	DataCota VARCHAR(11) NOT NULL,
	Valor DECIMAL(10,2) NOT NULL,
	VariacaoDum VARCHAR(10) NOT NULL,
	VariacaoPrimeiraData VARCHAR(10) NOT NULL
)